### ISSUE TITLE
Adjust Custom Fan Card for Air Purifiers

### ISSUE THREAD

**Issue by 13robin37** [UI-Lovelace-Minimalist/UI#107]
Currently the custom_card_saxel_fan by @saxel works only for traditional fans (which is fine), however Air Purifiers like the [Xiaomi](https://www.home-assistant.io/integrations/xiaomi_miio/#xiaomi-air-purifier-air-humidifier-and-standing-fan) ones work with the fan integration for the most part as well.

In my opinion the current button which triggers call-service fan.osciallate should switch between fan modes Off and Auto for purifiers. Should I set up a new custom card or integrate something within the existing card?

**Comment by CM000n** [comment]
Thank you so much for figuring this out! In my opinion, we should avoid redundant cards that look the same and do the same thing, just a little differently.
So I would rather prefer the second solution by feeling. But let's wait for the feedback from @saxel. Maybe he has another opinion about it.

**Comment by saxel** [comment]
Hello, sorry for the delayed response (just got back from a short vacation, also dealing with aftermath from flooding reaching into my apartment). I also have the same brand of air purifier but I haven't found a use case for controlling fan speed and off/auto. Mine is strictly controlled via automations.

I suppose if you want to control the air purifier fan speed with a slider then I agree with @CM000n that the 2nd suggestion makes sense, if it is okay that the slider is visible even when the air purifier fan speed is set to Auto.

@13robin37 do you want to give it a try with implementing? Otherwise I can have a look either later today or within a couple of days depending on my time available.

**Comment by 13robin37** [comment]
@saxel I will try to implement something in the next few days when I have some free time.

**Comment by 13robin37** [comment]
Apologies for the delay on this one, we've moved and I'm slowly picking up speed on Home Assistant projects again! 🙃

**Comment by lucasfr** [comment]
I'm not sure whether I am missing something but it would also be good to hide the oscillate button. Could not find anything in the docs.

**Comment by wilbiev** [comment]
Cleaning up issue list
