### ISSUE TITLE
card_scenes_welcome - Button-card JS error

### ISSUE THREAD

**Issue by spluft** [UI-Lovelace-Minimalist/UI#1195]
I got error:
```
button-card.js:425 ButtonCardJSTemplateError: TypeError: Cannot read properties of undefined (reading 'entity_id') in 'if(entity.entity_id.startsWith("scene.")){
    return "scene.turn_on"
  }
```

**Comment by LaUr3nTiU** [comment]
This issue is still present.

This happens when we provide less than 7 entities. Below is one example which passes a null entity which makes button-card to fail:

`entity: "[[[ return variables.entity_7.entity_id ]]]"`

is there any possibility to conditionalize item7 (or any other items for that matter)?

**Comment by wilbiev** [comment]
Cleaning-up old issues from the list. Let me know when this issue needs to be re-opened.
