### ISSUE TITLE
Images of the Washer/Dryer/Dishwasher Custom-card don't show up on https://ui-lovelace-minimalist.github.io/UI

### ISSUE THREAD

**Issue by Cruguah** [UI-Lovelace-Minimalist/UI#1252]
**Describe the bug**
The images of the Washer/Dryer/Dishwasher Custom-card don't show up when you look at https://ui-lovelace-minimalist.github.io/UI
The images do show up when you look at the github page (https://github.com/UI-Lovelace-Minimalist/UI/tree/main/custom_cards/custom_card_haven_washer) or (https://github.com/UI-Lovelace-Minimalist/UI/blob/main/docs/usage/custom_cards/custom_card_haven_washer.md)

Looking at the image path, they all look the same on the github site directly, but they seem to be adjusted on the https://ui-lovelace-minimalist.github.io/UI page

**To Reproduce**

1. Go to 'https://ui-lovelace-minimalist.github.io/UI/usage/custom_cards/custom_card_haven_washer/'
2. And see there are no images.
3. If you go to https://github.com/UI-Lovelace-Minimalist/UI/blob/main/docs/usage/custom_cards/custom_card_haven_washer.md
4. You do see the images

**Expected behavior**
I expect to see images on both places

**Screenshots**
![image](https://user-images.githubusercontent.com/14362766/230364534-8297a39b-f8f9-4e7a-ad6b-f14a03e1ae0f.png)

**Additional context**

**Comment by basbruss** [comment]
@Cruguah 

I think you will need to use markdown image notation instead of adding HTML-code to let it work in mkdocs.

<img width="878" alt="image" src="https://user-images.githubusercontent.com/68892092/230365972-550cf6a1-e84a-4db5-8b2c-fd7fc592e3a9.png">

versus correct code:
<img width="553" alt="image" src="https://user-images.githubusercontent.com/68892092/230366083-e77a4186-9c18-43d9-8d57-033bf6351c4d.png">

**Comment by Cruguah** [comment]
Thnx @basbruss, Problem solved in a new PR!
