### ISSUE TITLE
Duplicate resurces

### ISSUE THREAD

**Issue by davidepanato** [UI-Lovelace-Minimalist/UI#374]
Hello all,
after installing this "theme" from HACS I keep getting errors in the logs linked to duplicated resources:
	•	https://xxx.duckdns.org/hacsfiles/button-card/button-card.js?hacstag=146194325342:1:38791 NotSupportedError: Cannot define multiple custom elements with the same tag name
	•	https://xxx.duckdns.org/hacsfiles/mini-graph-card/mini-graph-card-bundle.js?hacstag=1512800620110:1:112277 NotSupportedError: Cannot define multiple custom elements with the same tag name
	•	https://xxx.duckdns.org/hacsfiles/my-cards/my-cards.js?hacstag=3991089019890349:162:74 NotSupportedError: Cannot define multiple custom elements with the same tag name
	•	https://xxx.duckdns.org/hacsfiles/lovelace-card-mod/card-mod.js?hacstag=190927524311:6:34168 NotSupportedError: Cannot define multiple custom elements with the same tag name

These components were previously installed in HACS without any problem, it seems they're conflicting with the ones inside custom_components/ui_lovelace_minimalist/cards.

How should this be handled? Do I have to remove the component from HACS?

Thanks

**Comment by CM000n** [comment]
Hello, we actually already have a warning that the included custom cards (Lovelace Resources) should not be installed if there is already installation for it via HACS, because then it can come exactly to this error: https://ui-lovelace-minimalist.github.io/UI/setup/installation/#install-integration
The easiest thing to do is to set up the integration again, this time without lovelace resources, if you have already installed them separately via HACS.

**Comment by davidepanato** [comment]
Perfect! This fixed my problem. Thanks a lot
