### ISSUE TITLE
I get an error when installing the theme using ui mode

### ISSUE THREAD

**Issue by PalmTamino** [UI-Lovelace-Minimalist/UI#553]
**Describe the bug**
I can't save after pasting the auto generated code

**To Reproduce**
Use the generator site and paste the code in the raw dashboard editor/do the tutorial with solution #2

**Expected behavior**
Saved and theme is working

**Screenshots**
![grafik](https://user-images.githubusercontent.com/36358673/160242856-86746333-c78a-424e-be37-68f92fbd0d3f.png)

**Comment by basbruss** [comment]
Hi,

I think you tried to install it with help of the deprecated wiki. This wiki is out of date since we were launched on HACS. Unfortunately we do not offer support anymore for UI-mode install as this limited by HA itself and is very error prone with updating.
Please use this wiki https://ui-lovelace-minimalist.github.io/UI/ to install and use this 'theme' 😉
