### ISSUE TITLE
In the downloaded and unpacked file you find a folder config

### ISSUE THREAD

**Issue by jwilleke** [UI-Lovelace-Minimalist/UI#560]
**Describe the bug**
There is no folder "config" as described in the documentation.
<https://ui-lovelace-minimalist.netlify.app/installation/yaml-mode>

_Upload to your HomeAssistant installation
In the downloaded and unpacked file you find a folder config
Move inside this folder and upload the two folders minimalist-templates and themes directly into your HA config folder_

**To Reproduce**

- Download the files
- Go to our repository on Github and download the code by pressing the green “Code” button in the top right corner and choose “Download ZIP”. Save the file on your computer and unpack it.
- Upload to your HomeAssistant installation (is this out of sequence?)
- In the downloaded and unpacked file you find a folder config <-- NOT THERE

**Expected behavior**
To be able to install the UI

**Screenshots**

<img width="240" alt="Screen Shot 2022-03-30 at 06 14 14" src="https://user-images.githubusercontent.com/3616688/160808557-3a4da6e0-e63b-4c32-9adc-ec162c5c94e0.png">

**Additional context**

**Comment by basbruss** [comment]
Hi,

You are referring to the deprecated wiki. The one should follow and is mentioned on the HA-forum and this github is: [ui-lovelace-minimalist.github.io/ui/](https://ui-lovelace-minimalist.github.io/UI/) . 
Since the HACS launch we use a different folder structure to accommodate the needs of HACS.

If you choose to install in manually we provide a zip with each release: https://github.com/UI-Lovelace-Minimalist/UI/releases/tag/v0.0.7-hotfix1 so you do not need to download all files of this github 😄 

Hope this helps you with installing this 'theme'

**Comment by basbruss** [comment]
> Please destroy the deprecated wiki. I'm sure many of us had the same issue.
> 
> Thx

That isn’t that easy as it seems like. If we where able to we could also update that wiki and have no need for the second one.

Unfortunely none of the active maintainers do have the rights to change the old wiki.
