### ISSUE TITLE
Translations for card_welcome_scenes / chip_weather_date are missing

### ISSUE THREAD

**Issue by agencetwogether** [UI-Lovelace-Minimalist/UI#575]
Do you know how to or can you implement translations for chip_weather_date inside card_welcome_scenes ?
eg Months abr are not in variables and so are hard coded

`const months = ["Jan", "Feb", "Mar","Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];`

And the format have to match the language
For example, French format is "day month", not "month day"

**Comment by basbruss** [comment]
Due to the fact that most common languages use very different date formatting it is pretty difficult to build an one fits all solution. That’s why it only supports the English formatting for now.

To fit your needs it’s probably best to copy the template and make a custom_card where you change it to the formatting of your language. Note: this can be somewhat advanced and requires a bit of knowledge of the custom:button-card and JavaScript templating. :wink:

**Comment by agencetwogether** [comment]
Thanks @basbruss . This is what I done.
And I agree with you. I thank someone could to do to give a complete card with translation compatibility but as you said it's difficult to manage language formatting.

So I custom card to my needs.
Thanks again 

Perhaps an idea to consider, create a custom sensor using (Python reference) [strftime] (https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes)
`nextsunset:
       friendly_name: 'Next Sunset'
       value_template: "{{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom('%D %-I:%M %P') }}"
       `

**Comment by kauelima** [comment]
Came here looking for this. I edited the chip code to better show date, but it reversed when I updated.

Looks like I need to do my own card. Maybe with this I can also put the weather in the chip.

Knowing that the format is not easy to edit, maybe the card should have an on/off switch for this chip.

**Comment by basbruss** [comment]
Should be fixed with #606
