### ISSUE TITLE
Chip in light theme cut off

### ISSUE THREAD

**Issue by damianeickhoff** [UI-Lovelace-Minimalist/UI#58]
In the light theme, the chip (for some reason not the first 2) is cut off because of the box-shadow.

I'm using the icon only chip, but also tried it with the normal generic chip, but that makes no difference.

Dark mode is fine, because there is no box-shadow. Also if I set the box-shadow to none in the light theme, the cut off is also gone, so something is up with that shadow.

![afbeelding](https://user-images.githubusercontent.com/12126826/144326486-93ffb2d2-05a5-4fd1-888b-bc85cce88001.png)

PS: This is my 3rd issue, sorry! I really like this theme, so far one of the best out there, so I want to make it even better :)

**Comment by rphlwnk** [comment]
It looks fine on my site (in Browser and on mobile), maybe share your config for the chips.

![image](https://user-images.githubusercontent.com/34039879/144498332-731ee2c8-e232-40a0-924f-2b8d14bf3e03.png)

**Comment by damianeickhoff** [comment]
Strange, will look into it, maybe its a config thingy. I'll close the issue for now.

**Comment by rphlwnk** [comment]
@damianeickhoff are you using the swipe-card card for the chips?

We have the same issue posted [in the forum](https://community.home-assistant.io/t/lovelace-ui-minimalist/322687/571) with the swipe-card mentioned and it's the swipe-card that breaks the box-shadow because it is basically outside of the box. 

![image](https://user-images.githubusercontent.com/34039879/145185120-532a7143-3429-4c03-8446-99622cb99bc2.png)

![image](https://user-images.githubusercontent.com/34039879/145185348-3c60c4a1-3d62-4342-b1e9-21f7304fa85b.png)

Since the swipe-card.js doesn't get an update so often, you can search for this line:

`.swiper-container{margin:0 auto;position:relative;overflow:hidden;list-style:none;padding:0;z-index:1}`

and replace the `overflow:hidden` with `overflow:visible`, now the box-shadow is shown correctly.

**Comment by damianeickhoff** [comment]
@rphlwnk no, its not the swipe-card but (I just found out) the state-switch card. I have changed, on your advice, the overflow to Visible in the state-switch.js file and reloaded the server, but that doens't do anything. 

The state-switch card also gives a flex so the icons are to far apart, but also changing that in the .js file doenst fix that problem.

I think the state-switch card is just, not good enough, for this awesome theme.

Nevertheless, thank you for your thoughts.
