### ISSUE TITLE
Minimalists mobile theme

### ISSUE THREAD

**Issue by Niiikoc** [UI-Lovelace-Minimalist/UI#641]
I found a bug in minimalist mobile theme.
When I enter to home assistant mobile app doesn't show slider menu bar as you can see in the short video.
But it works fine with minimalist desktop theme.

I am running the latest version of minimalist and the latest version of ha core-2022.5.0

https://user-images.githubusercontent.com/24290051/167035982-c2346ab8-a2b9-45e5-a9bb-a92d460d8f77.mp4

**Comment by MichaelBrunn3r** [comment]
Is this related to #647 ? What theme are you using? Is the issue only present in dark or light mode?

**Comment by benyaming** [comment]
@MichaelBrunn3r Same issue for me.

Tried to use mobile, mobile-tapbar and ios-tapbar with both light and dark modes.
Also, on mobile (w/o tapbar) theme there is no availability to navigate through dashboard tabs.

**Comment by MichaelBrunn3r** [comment]
@benyaming Hm, so you still can't see the sliders? I fixed that bug a month ago, but maybe this is a new related one. Could you elaborate more on that? Maybe some screenshots might help. Do you have the latest version of minimalist installed?

Also I'm not quite sure I understand your second issue. The themes without a tapbar do not offer any navigation to other tabs in the same dashboard, yes. But that is, as I understand it, intentional. You either have to use a tapbar theme, or create cards that redirect you to another tab (e.g. a "living room" card that navigates you to the "living room" tab, a "back" button that navigates you back to the home tab of the dashboard).

**Comment by benyaming** [comment]
@MichaelBrunn3r Ok, I understood about tapbar themes, my bad.

Regarding main menu navigation, [here you are](https://youtu.be/uaJHoAR35yE ) (sorry for Russian ui, it should not be a problem)

**Comment by MichaelBrunn3r** [comment]
It seems the tapbar appears but there are no tabs on it. I think this is an entirely different problem. It would be best if you created a new issue for it

**Comment by benyaming** [comment]
@MichaelBrunn3r again, I'm taking about non-tapbar themes - the problem that there is no side menu button in these themes

**Comment by ingeniumdesign** [comment]
check this solution: https://github.com/UI-Lovelace-Minimalist/UI/issues/1157
