### ISSUE TITLE
Graph Card / Binary Sensor Card not working properly on v1.0.0-hotfix

### ISSUE THREAD

**Issue by Gitarcitano** [UI-Lovelace-Minimalist/UI#769]
**Describe the bug**
- In the Graph Card:
  - The variable `ulm_card_graph_name` and `ulm_card_graph_entity` stoped working (screenshot 1)
- Binary Sensor Card: 
  - Stopped working with numeric states (like illuminance) (screenshot 2)
  - Using `show_last_changed: true` will render the text two times, or render the component again (screenshot 3)
  - Stopped showing the custom name with `name` property

**To Reproduce**

1. Update from 0.0.9 to 1.0.0-hotfix
2. Go through the old graph cards or binary sensor cards

**Expected behavior**
It should continue to work normally as there was no breaking change warning for these components

**Screenshots**
Screenshot 1
<img width="503" alt="image" src="https://user-images.githubusercontent.com/44866256/175097669-1ccd4659-91c9-47a7-9696-40eec70a30f7.png">

Screenshot 2
<img width="263" alt="image" src="https://user-images.githubusercontent.com/44866256/175097723-ef7f6d7e-6e62-498d-8f54-490cf4c75b91.png">

Screenshot 3
<img width="519" alt="image" src="https://user-images.githubusercontent.com/44866256/175097965-fc152754-6e31-453f-8f78-51b092c1c0b6.png">

**Additional context**
All my states are reporting the data normally
<img width="688" alt="image" src="https://user-images.githubusercontent.com/44866256/175098371-0e6d89f6-2897-4ea2-a378-848db85291a2.png">

Edit: The same components after revert to 0.0.9:

<img width="521" alt="image" src="https://user-images.githubusercontent.com/44866256/175100551-f8bcb22f-2d62-47f6-a77e-247d887cd46f.png">
<img width="263" alt="image" src="https://user-images.githubusercontent.com/44866256/175100515-e20a17b0-6396-4988-b426-830f69d169b2.png">
<img width="505" alt="image" src="https://user-images.githubusercontent.com/44866256/175100597-de10b8e8-6052-456b-94bb-02835efe0484.png">

**Comment by schumijo** [comment]
Hi @Gitarcitano 
Thank you for opening this issue. About show_last_changed option, it was the most difficult part to modify with the new custom actions. I have the same problem on my dev environment during a long time...and I thought it was solved.
I will take a look quickly next days.

This release has a lot of improvements so other errors needs some investigation

**Comment by Qpernicus** [comment]
I have a similar problem but the card (same types) are also complaining there is no custom_actions.yaml template, even tho I created that file (and folder) manually. Is that a sign the installation went sour? Or am I forgetting a step? (In the cards I don't put any referral to the template in the cards, but when I do, I can't seem to find where to put it. Every spot gives an error (added to template: line, to the variables part. ).

**Comment by basbruss** [comment]
There are some unforeseen issues with `v1.0.0`. The release is rolled back. For now, it's best practice to re-download `v0.09` and wait until there is a new release that fixes the known issues.

**Comment by basbruss** [comment]
Solved with #770

**Comment by Qpernicus** [comment]
Hate to reopen stuff but because it's about this:

1) The ulm_card_graph_name variable doesn't seem to work. All my graphs show the entity name. The CUSTOM Power Details card does follow its name variable

2) How is the translation handled? I have a few entities that show in English even tho I have my HA set to Dutch (CUSTOM person info card & the room card with a update entity as a 'state' entity.. All the custom cards still have a translations.yaml (NL.yaml) file. Is this still needed?

**Comment by basbruss** [comment]
> 1. The ulm_card_graph_name variable doesn't seem to work. All my graphs show the entity name. The CUSTOM Power Details card does follow its name variable

This is probably due to changing the old framework to a more nested variant, so the variable needs an additional passthrough. (Will be fixed with the upcoming releases)

> 2\. How is the translation handled? I have a few entities that show in English even tho I have my HA set to Dutch (CUSTOM person info card & the room card with an update entity as a 'state' entity.. All the custom cards still have a translations.yaml (NL.yaml) file. Is this still needed?

Not all custom cards are adapted to the new translation engine. So some of the translation files could be considered deprecated but are still in place to provide failbacks for users on older versions of the custom cards.
The translation engine only translates states and most of the strings which were available in the languages files. It can not translate the names of entities and strings provided by end-users in variables.

**Comment by Qpernicus** [comment]
> > 1. The ulm_card_graph_name variable doesn't seem to work. All my graphs show the entity name. The CUSTOM Power Details card does follow its name variable
> 
> 
> 
> This is probably due to changing the old framework to a more nested variant, so the variable needs an additional passthrough. (Will be fixed with the upcoming releases)
> 
> 
> 
> > 2\. How is the translation handled? I have a few entities that show in English even tho I have my HA set to Dutch (CUSTOM person info card & the room card with an update entity as a 'state' entity.. All the custom cards still have a translations.yaml (NL.yaml) file. Is this still needed?
> 
> 
> 
> Not all custom cards are adapted to the new translation engine. So some of the translation files could be considered deprecated but are still in place to provide failbacks for users on older versions of the custom cards.
> 
> The translation engine only translates states and most of the strings which were available in the languages files. It can not translate the names of entities and strings provided by end-users in variables.

1) Great. That's clear. 
2) The state of the person_info card or the person.entity is 'home' which should be Thuis. So it's the state that's not correct. In the GitHub of the card (in the custom section or UI) is the mention of added translation on top. Does that mean the card should be adapted? Same goes for the room card with the update entity. It shows the state as 'off' instead of 'uit'. Other room cards with other entities do show as 'uit'. So I have 9 room cards of which 1 has Off and the other 8 are Uit.
