### ISSUE TITLE
Custom_card_person_info - charging symbol state not working

### ISSUE THREAD

**Issue by Boabee** [UI-Lovelace-Minimalist/UI#883]
Custom Card - Person info
Not reporting the battery state with correct symbol from the companion app. Not reporting If device is charging or not.

I am using IOS companion app, the entity's state is updating correctly and in 20 second intervals as set by device.

In the UI the symbol only indicates battery level and will not produce charging symbol (lighting bolt)

**Comment by aehru** [comment]
Are you sure that your are passing the `sensor.your_phone_battery_status` entity to `ulm_card_person_battery_state_entity` and not the `sensor.your_phone_battery_charger_type` ?
As the custom card - person info use the state of `ulm_card_person_battery_state_entity` and compare it to `charging` only in order to determine if it is charging the `sensor.your_phone_battery_status` will not work (because it returns ac/wireless).

I've tested it with and Android Phone (no iPhone for testing right now) and everything is working well.
